import { defaultUrlTransform } from "react-markdown"

/**
 * react-markdown sanitizes every URL through `defaultUrlTransform`, which only
 * lets http/https/mailto/xmpp/irc through and rewrites everything else to "".
 *
 * Charts generated by the coder come back from the sandbox as inline base64 —
 * `![outputs/plots/chart.png](data:image/png;base64,...)` — so the default
 * transform blanked the src and the browser rendered a broken image showing
 * only the alt text. Nothing errored; the chart just silently never appeared.
 *
 * Allow base64 image payloads, and keep the default sanitization for
 * everything else so other protocols stay blocked. SVG is included because an
 * `<img>` never executes scripts embedded in its source.
 */
const BASE64_IMAGE_URI = /^data:image\/(?:png|jpe?g|gif|webp|svg\+xml);base64,[A-Za-z0-9+/=\s]+$/i

export function markdownUrlTransform(url: string): string | null | undefined {
  if (BASE64_IMAGE_URI.test(url)) {
    return url
  }
  return defaultUrlTransform(url)
}
